logging:
  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"
  level:
    org.springframework.web: ERROR
    com.example.demo: DEBUG
    org.hibernate: ERROR
  file:
    name: logs/application-debug.log

backend:
  server:
    http://localhost
  port:
    5432